<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbTransaction" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://www.bwr.mx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/Ejercicio04A/Ejercicio04A/BPELInvoice"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/dbTransaction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbTransaction.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InvoiceHeaderCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbTransaction"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BPELInvoice.wsdl"/>
            <oracle-xsl-mapper:rootElement name="input" namespace="http://www.bwr.mx"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BPELInvoice.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListInvoice" namespace="http://www.bwr.mx"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE APR 06 11:24:13 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
   <xsl:template match="/">
      <ns1:ListInvoice>
         <xsl:for-each select="/ns0:InvoiceHeaderCollection/ns0:InvoiceHeader">
            <xsl:if test="ns0:rfc = $inputVariable.payload/ns1:input/ns1:rfc">
               <ns1:Invoice>
                  <ns1:InvoiceDate>
                     <xsl:value-of select="$inputVariable.payload/ns1:input/ns1:rfc"/>
                  </ns1:InvoiceDate>
                  <ns1:RFC>
                     <xsl:value-of select="$inputVariable.payload/ns1:input/ns1:fecha"/>
                  </ns1:RFC>
                  <ns1:InvoiceAmount/>
                  <ns1:InvoiceTaxAmount/>
                  <ns1:UUID/>
               </ns1:Invoice>
            </xsl:if>
         </xsl:for-each>
      </ns1:ListInvoice>
   </xsl:template>
</xsl:stylesheet>
