<wsdl:definitions
     name="getCustDetails"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getCustDetails"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getCustDetails"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCustDetails"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getCustDetails_plt" >
    <plt:role name="getCustDetails_role" >
      <plt:portType name="tns:getCustDetails_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCustDetails" schemaLocation="../Schemas/getCustDetails_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getCustDetailsSelect_inputParameters">
        <wsdl:part name="getCustDetailsSelect_inputParameters" element="top:getCustDetailsSelect_rfcInputParameters"/>
    </wsdl:message>
    <wsdl:message name="FinCustDetailsCollection_msg">
        <wsdl:part name="FinCustDetailsCollection" element="top:FinCustDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="getCustDetails_ptt">
        <wsdl:operation name="getCustDetailsSelect">
            <wsdl:input message="tns:getCustDetailsSelect_inputParameters"/>
            <wsdl:output message="tns:FinCustDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
