<wsdl:definitions
     name="getFolioFromRFC"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getFolioFromRFC"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getFolioFromRFC"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getFolioFromRFC"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getFolioFromRFC_plt" >
    <plt:role name="getFolioFromRFC_role" >
      <plt:portType name="tns:getFolioFromRFC_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getFolioFromRFC" schemaLocation="../Schemas/getFolioFromRFC_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getFolioFromRFCSelect_inputParameters">
        <wsdl:part name="getFolioFromRFCSelect_inputParameters" element="top:getFolioFromRFCSelect_date_rfcInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InvoiceHeaderCollection_msg">
        <wsdl:part name="InvoiceHeaderCollection" element="top:InvoiceHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="getFolioFromRFC_ptt">
        <wsdl:operation name="getFolioFromRFCSelect">
            <wsdl:input message="tns:getFolioFromRFCSelect_inputParameters"/>
            <wsdl:output message="tns:InvoiceHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
