<wsdl:definitions
     name="getInvoiceDetail"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getInvoiceDetail"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getInvoiceDetail"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getInvoiceDetail"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getInvoiceDetail_plt" >
    <plt:role name="getInvoiceDetail_role" >
      <plt:portType name="tns:getInvoiceDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getInvoiceDetail" schemaLocation="../Schemas/getInvoiceDetail_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getInvoiceDetailSelect_inputParameters">
        <wsdl:part name="getInvoiceDetailSelect_inputParameters" element="top:getInvoiceDetailSelect_folioInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InvoiceDetailsCollection_msg">
        <wsdl:part name="InvoiceDetailsCollection" element="top:InvoiceDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="getInvoiceDetail_ptt">
        <wsdl:operation name="getInvoiceDetailSelect">
            <wsdl:input message="tns:getInvoiceDetailSelect_inputParameters"/>
            <wsdl:output message="tns:InvoiceDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
