<wsdl:definitions
     name="getInvoiceHeader"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getInvoiceHeader"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejercicio04A/Ejercicio04A/getInvoiceHeader"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getInvoiceHeader"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getInvoiceHeader_plt" >
    <plt:role name="getInvoiceHeader_role" >
      <plt:portType name="tns:getInvoiceHeader_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getInvoiceHeader" schemaLocation="../Schemas/getInvoiceHeader_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getInvoiceHeaderSelect_inputParameters">
        <wsdl:part name="getInvoiceHeaderSelect_inputParameters" element="top:getInvoiceHeaderSelect_dateInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InvoiceHeaderCollection_msg">
        <wsdl:part name="InvoiceHeaderCollection" element="top:InvoiceHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="getInvoiceHeader_ptt">
        <wsdl:operation name="getInvoiceHeaderSelect">
            <wsdl:input message="tns:getInvoiceHeaderSelect_inputParameters"/>
            <wsdl:output message="tns:InvoiceHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
