<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.bwr.mx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/Ejercicio05B/Ejercicio05B/BPELFtp"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BPELFtp.wsdl"/>
            <oracle-xsl-mapper:rootElement name="expenses" namespace="http://www.bwr.mx"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BPELFtp.wsdl"/>
            <oracle-xsl-mapper:rootElement name="expenses" namespace="http://www.bwr.mx"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED APR 07 17:01:22 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:expenses id="{/ns0:expenses/@id}"
                    fecha="{concat (substring (/ns0:expenses/@fecha, 7, 4 ), substring (/ns0:expenses/@fecha, 4, 2 ), substring (/ns0:expenses/@fecha, 1, 2 ) )}">
         <ns0:rows>
            <xsl:for-each select="/ns0:expenses/ns0:rows/ns0:row">
               <xsl:sort select="ns0:country"/>
               <ns0:row>
                  <ns0:uuid>
                     <xsl:value-of select="ns0:uuid"/>
                  </ns0:uuid>
                  <ns0:number_tdc>
                     <xsl:value-of select="ns0:number_tdc"/>
                  </ns0:number_tdc>
                  <ns0:amount>
                     <xsl:value-of select="ns0:amount"/>
                  </ns0:amount>
                  <xsl:for-each select="ns0:tax">
                     <ns0:tax>
                        <xsl:value-of select="self::node()"/>
                     </ns0:tax>
                  </xsl:for-each>
                  <ns0:country>
                     <xsl:value-of select="ns0:country"/>
                  </ns0:country>
               </ns0:row>
            </xsl:for-each>
         </ns0:rows>
      </ns0:expenses>
   </xsl:template>
</xsl:stylesheet>
