<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://xmlns.oracle.com/ns/order" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://oracle.com/sca/soapservice/POProcessing/POProcessing/recibePO">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/po.xsd"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/recibePO.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI MAR 12 13:59:56 CST 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:PurchaseOrder>
         <ns0:CustID>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:CustID"/>
         </ns0:CustID>
         <ns0:ID>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ID"/>
         </ns0:ID>
         <ns0:productName>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:productName"/>
         </ns0:productName>
         <ns0:itemType>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:itemType"/>
         </ns0:itemType>
         <ns0:price>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:price"/>
         </ns0:price>
         <ns0:quantity>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:quantity"/>
         </ns0:quantity>
         <ns0:status>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:status"/>
         </ns0:status>
         <ns0:ccType>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccType"/>
         </ns0:ccType>
         <ns0:ccNumber>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccNumber"/>
         </ns0:ccNumber>
      </ns0:PurchaseOrder>
   </xsl:template>
</xsl:stylesheet>
