<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://xmlns.oracle.com/ns/fulfillment" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/ns/order" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://oracle.com/sca/soapservice/POProcessing/POProcessing/recibePO"
                xmlns:client="http://xmlns.oracle.com/POProcessing/POProcessing/FulfillmentProcess"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/recibePO.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FulfillmentProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Fulfillment" namespace="http://xmlns.oracle.com/ns/fulfillment"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI MAR 12 00:51:47 CST 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Fulfillment>
         <tns:customerId>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:CustID"/>
         </tns:customerId>
         <tns:orderId>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ID"/>
         </tns:orderId>
         <tns:total>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:price * /ns0:PurchaseOrder/ns0:quantity"/>
         </tns:total>
      </tns:Fulfillment>
   </xsl:template>
</xsl:stylesheet>
